import { images } from "./images.js";

export const products = [
  {
    id: "whistle",
    name: "صافرة كشفية نحاسية",
    description: "صافرة معدنية متينة للاستخدام في المخيمات والتجمعات.",
    price: 85,
    image: images.products.whistle,
    category: "الإكسسوارات",
    featured: true,
  },
  {
    id: "scarf",
    name: "منديل كشفي مطرز",
    description: "منديل مطرز بألوان الفريق وشعار كشافة أبطال العجايبي.",
    price: 120,
    image: images.products.scarf,
    category: "الزي الكشفي",
    featured: true,
  },
  {
    id: "uniform",
    name: "زي كشفي كامل",
    description: "قميص وبنطلون رسمي بشارات الفريق والكنيسة.",
    price: 450,
    image: images.products.uniform,
    category: "الزي الكشفي",
    featured: true,
  },
  {
    id: "belt",
    name: "حزام كشفي جلدي",
    description: "حزام جلد طبيعي بإبزيم معدني محفور بشعار الكشافة.",
    price: 160,
    image: images.products.belt,
    category: "الإكسسوارات",
    featured: true,
  },
  {
    id: "scout-bag",
    name: "حقيبة كشفية",
    description: "حقيبة عملية للرحلات والمخيمات اليومية.",
    price: 280,
    image: images.products.uniform,
    category: "الأدوات",
  },
  {
    id: "scout-cap",
    name: "كاب كشفي",
    description: "كاب مريح بشعار الفريق للاستخدام اليومي.",
    price: 95,
    image: images.products.scarf,
    category: "الزي الكشفي",
  },
  {
    id: "scout-shirt",
    name: "تيشيرت كشفي",
    description: "تيشيرت قطني بطباعة كشفية بسيطة وأنيقة.",
    price: 180,
    image: images.products.uniform,
    category: "الزي الكشفي",
  },
  {
    id: "scout-mug",
    name: "كوب كشفي",
    description: "كوب تذكاري مناسب للرحلات والهدايا.",
    price: 110,
    image: images.products.whistle,
    category: "الهدايا",
  },
  {
    id: "scout-badge",
    name: "شارة كشفية",
    description: "شارة مطرزة لإكمال الزي الكشفي.",
    price: 45,
    image: images.products.belt,
    category: "الشارات",
  },
  {
    id: "scout-notebook",
    name: "دفتر كشفي",
    description: "دفتر ملاحظات صغير للتدريب والرحلات.",
    price: 60,
    image: images.products.whistle,
    category: "الأدوات",
  },
  {
    id: "scout-medal",
    name: "ميدالية كشفية",
    description: "ميدالية تذكارية بطابع كشفي أصيل.",
    price: 75,
    image: images.products.belt,
    category: "الهدايا",
  },
  {
    id: "scout-accessories",
    name: "أدوات كشفية متنوعة",
    description: "مجموعة إكسسوارات صغيرة للأنشطة الكشفية.",
    price: 130,
    image: images.products.scarf,
    category: "الأدوات",
  },
];
